name: parkplannerproject
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.5.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  flutter_osm_plugin: ^0.53.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
